In [1]:
import cv2

In [2]:
cv2


<module 'cv2.cv2' from '/home/uday/anaconda3/lib/python3.7/site-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so'>

In [3]:
from cv2 import cv2


img = cv2.imread('galaxy.jpg', 0)
print(type(img))
print(img)
print(img.shape)
print(img.ndim)

<class 'numpy.ndarray'>
[[14 18 14 ... 20 15 16]
 [12 16 12 ... 20 15 17]
 [12 13 16 ... 14 24 21]
 ...
 [ 0  0  0 ...  5  8 14]
 [ 0  0  0 ...  2  3  9]
 [ 1  1  1 ...  1  1  3]]
(1485, 990)
2


In [8]:
resized_image = cv2.resize(img, (int(img.shape[1]/2), int(img.shape[0]/2)))
cv2.imshow("Galaxy", resized_image)
cv2.imwrite("Galaxy_resized.jpg", resized_image)
cv2.waitKey(5000)
cv2.destroyAllWindows()